import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { CATEGORY_LABELS, RUBRIC_CATEGORIES, type RubricCategory } from "./rubric";

const styles = StyleSheet.create({
  page: { padding: 56, fontSize: 11, fontFamily: "Helvetica", color: "#0a0a0a" },
  brand: { fontSize: 10, color: "#737373", marginBottom: 24, letterSpacing: 1.2 },
  h1: { fontSize: 28, fontWeight: "bold", marginBottom: 8 },
  url: { fontSize: 11, color: "#525252", marginBottom: 24 },
  score: { fontSize: 64, fontWeight: "bold", letterSpacing: -1, marginBottom: 4 },
  scoreLabel: { fontSize: 10, color: "#737373", textTransform: "uppercase", marginBottom: 28, letterSpacing: 1 },
  section: { marginBottom: 18 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 10 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  rowLabel: { fontSize: 11 },
  rowValue: { fontSize: 11, fontWeight: "bold" },
  recCard: { marginBottom: 10, padding: 10, backgroundColor: "#fafafa", borderRadius: 4 },
  recPriority: { fontSize: 9, color: "#737373", textTransform: "uppercase", letterSpacing: 1 },
  recAction: { fontSize: 12, fontWeight: "bold", marginTop: 4 },
  recRationale: { fontSize: 10, color: "#525252", marginTop: 4, lineHeight: 1.4 },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 56,
    right: 56,
    fontSize: 9,
    color: "#a3a3a3",
    textAlign: "center",
  },
});

type Recommendation = {
  category: RubricCategory;
  priority: "high" | "medium" | "low";
  action: string;
  rationale: string;
};

export function AuditPdf(props: {
  url: string;
  overallScore: number;
  scores: Record<RubricCategory, number>;
  recommendations: Recommendation[];
}) {
  return (
    <Document title="Rebuild Engine Audit">
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.brand}>REBUILD ENGINE · CONVERSION AUDIT</Text>
        <Text style={styles.h1}>Your audit</Text>
        <Text style={styles.url}>{props.url}</Text>

        <Text style={styles.score}>{props.overallScore}/100</Text>
        <Text style={styles.scoreLabel}>Overall conversion score</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Category breakdown</Text>
          {RUBRIC_CATEGORIES.map((c) => (
            <View key={c} style={styles.row}>
              <Text style={styles.rowLabel}>{CATEGORY_LABELS[c]}</Text>
              <Text style={styles.rowValue}>{props.scores[c]}/10</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Top recommendations</Text>
          {props.recommendations.map((r, i) => (
            <View key={i} style={styles.recCard} wrap={false}>
              <Text style={styles.recPriority}>
                {r.priority} · {CATEGORY_LABELS[r.category]}
              </Text>
              <Text style={styles.recAction}>{r.action}</Text>
              <Text style={styles.recRationale}>{r.rationale}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer} fixed>
          Generated by Rebuild Engine · convelabs.com
        </Text>
      </Page>
    </Document>
  );
}
